### ISSUE TITLE
"Java and Kotlin" title change

### ISSUE THREAD

**Issue by skaldebane** [mackuba/sdk.blue#2]
This might not be that big of a deal, but since the "Java and Kotlin" only lists Kotlin Multiplatform libraries, which, while they may be possible to use in Java, are designed for Kotlin usage first and foremost, and can also be used from other targets Kotlin interoperates with (Swift and Obj-C, partially JS / C), I think it should just be called "Kotlin".

If that's not desired (e.g. due to lack of Java options), at the very least they could be flipped, so just like "Swift & Obj-C", this would become "Kotlin & Java". I can open a PR if desired :D

It's a minor thing, so take it with a grain of salt!

**Comment by mackuba** [comment]
Hmm, good point I guess 🤔 I'll change that.
